# Complete list of countries and their states/provinces
COUNTRIES = [
    ('', 'Select Country'),
    ('Afghanistan', 'Afghanistan'),
    ('Albania', 'Albania'),
    ('Algeria', 'Algeria'),
    ('Andorra', 'Andorra'),
    ('Angola', 'Angola'),
    ('Argentina', 'Argentina'),
    ('Armenia', 'Armenia'),
    ('Australia', 'Australia'),
    ('Austria', 'Austria'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahamas', 'Bahamas'),
    ('Bahrain', 'Bahrain'),
    ('Bangladesh', 'Bangladesh'),
    ('Barbados', 'Barbados'),
    ('Belarus', 'Belarus'),
    ('Belgium', 'Belgium'),
    ('Belize', 'Belize'),
    ('Benin', 'Benin'),
    ('Bhutan', 'Bhutan'),
    ('Bolivia', 'Bolivia'),
    ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'),
    ('Botswana', 'Botswana'),
    ('Brazil', 'Brazil'),
    ('Brunei', 'Brunei'),
    ('Bulgaria', 'Bulgaria'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodia', 'Cambodia'),
    ('Cameroon', 'Cameroon'),
    ('Canada', 'Canada'),
    ('Cape Verde', 'Cape Verde'),
    ('Central African Republic', 'Central African Republic'),
    ('Chad', 'Chad'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Colombia', 'Colombia'),
    ('Comoros', 'Comoros'),
    ('Congo', 'Congo'),
    ('Costa Rica', 'Costa Rica'),
    ('Croatia', 'Croatia'),
    ('Cuba', 'Cuba'),
    ('Cyprus', 'Cyprus'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Djibouti', 'Djibouti'),
    ('Dominica', 'Dominica'),
    ('Dominican Republic', 'Dominican Republic'),
    ('Ecuador', 'Ecuador'),
    ('Egypt', 'Egypt'),
    ('El Salvador', 'El Salvador'),
    ('Equatorial Guinea', 'Equatorial Guinea'),
    ('Eritrea', 'Eritrea'),
    ('Estonia', 'Estonia'),
    ('Ethiopia', 'Ethiopia'),
    ('Fiji', 'Fiji'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('Gabon', 'Gabon'),
    ('Gambia', 'Gambia'),
    ('Georgia', 'Georgia'),
    ('Germany', 'Germany'),
    ('Ghana', 'Ghana'),
    ('Greece', 'Greece'),
    ('Grenada', 'Grenada'),
    ('Guatemala', 'Guatemala'),
    ('Guinea', 'Guinea'),
    ('Guinea-Bissau', 'Guinea-Bissau'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'),
    ('Honduras', 'Honduras'),
    ('Hungary', 'Hungary'),
    ('Iceland', 'Iceland'),
    ('India', 'India'),
    ('Indonesia', 'Indonesia'),
    ('Iran', 'Iran'),
    ('Iraq', 'Iraq'),
    ('Ireland', 'Ireland'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japan'),
    ('Jordan', 'Jordan'),
    ('Kazakhstan', 'Kazakhstan'),
    ('Kenya', 'Kenya'),
    ('Kiribati', 'Kiribati'),
    ('Kosovo', 'Kosovo'),
    ('Kuwait', 'Kuwait'),
    ('Kyrgyzstan', 'Kyrgyzstan'),
    ('Laos', 'Laos'),
    ('Latvia', 'Latvia'),
    ('Lebanon', 'Lebanon'),
    ('Lesotho', 'Lesotho'),
    ('Liberia', 'Liberia'),
    ('Libya', 'Libya'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lithuania', 'Lithuania'),
    ('Luxembourg', 'Luxembourg'),
    ('Macedonia', 'Macedonia'),
    ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'),
    ('Malaysia', 'Malaysia'),
    ('Maldives', 'Maldives'),
    ('Mali', 'Mali'),
    ('Malta', 'Malta'),
    ('Marshall Islands', 'Marshall Islands'),
    ('Mauritania', 'Mauritania'),
    ('Mauritius', 'Mauritius'),
    ('Mexico', 'Mexico'),
    ('Micronesia', 'Micronesia'),
    ('Moldova', 'Moldova'),
    ('Monaco', 'Monaco'),
    ('Mongolia', 'Mongolia'),
    ('Montenegro', 'Montenegro'),
    ('Morocco', 'Morocco'),
    ('Mozambique', 'Mozambique'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namibia'),
    ('Nauru', 'Nauru'),
    ('Nepal', 'Nepal'),
    ('Netherlands', 'Netherlands'),
    ('New Zealand', 'New Zealand'),
    ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'),
    ('Nigeria', 'Nigeria'),
    ('North Korea', 'North Korea'),
    ('Norway', 'Norway'),
    ('Oman', 'Oman'),
    ('Pakistan', 'Pakistan'),
    ('Palau', 'Palau'),
    ('Palestine', 'Palestine'),
    ('Panama', 'Panama'),
    ('Papua New Guinea', 'Papua New Guinea'),
    ('Paraguay', 'Paraguay'),
    ('Peru', 'Peru'),
    ('Philippines', 'Philippines'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Qatar', 'Qatar'),
    ('Romania', 'Romania'),
    ('Russia', 'Russia'),
    ('Rwanda', 'Rwanda'),
    ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'),
    ('Samoa', 'Samoa'),
    ('San Marino', 'San Marino'),
    ('Sao Tome and Principe', 'Sao Tome and Principe'),
    ('Saudi Arabia', 'Saudi Arabia'),
    ('Senegal', 'Senegal'),
    ('Serbia', 'Serbia'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Sierra Leone'),
    ('Singapore', 'Singapore'),
    ('Slovakia', 'Slovakia'),
    ('Slovenia', 'Slovenia'),
    ('Solomon Islands', 'Solomon Islands'),
    ('Somalia', 'Somalia'),
    ('South Africa', 'South Africa'),
    ('South Korea', 'South Korea'),
    ('South Sudan', 'South Sudan'),
    ('Spain', 'Spain'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Sudan', 'Sudan'),
    ('Suriname', 'Suriname'),
    ('Swaziland', 'Swaziland'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Syria', 'Syria'),
    ('Taiwan', 'Taiwan'),
    ('Tajikistan', 'Tajikistan'),
    ('Tanzania', 'Tanzania'),
    ('Thailand', 'Thailand'),
    ('Timor-Leste', 'Timor-Leste'),
    ('Togo', 'Togo'),
    ('Tonga', 'Tonga'),
    ('Trinidad and Tobago', 'Trinidad and Tobago'),
    ('Tunisia', 'Tunisia'),
    ('Turkey', 'Turkey'),
    ('Turkmenistan', 'Turkmenistan'),
    ('Tuvalu', 'Tuvalu'),
    ('Uganda', 'Uganda'),
    ('Ukraine', 'Ukraine'),
    ('United Arab Emirates', 'United Arab Emirates'),
    ('United Kingdom', 'United Kingdom'),
    ('United States', 'United States'),
    ('Uruguay', 'Uruguay'),
    ('Uzbekistan', 'Uzbekistan'),
    ('Vanuatu', 'Vanuatu'),
    ('Vatican City', 'Vatican City'),
    ('Venezuela', 'Venezuela'),
    ('Vietnam', 'Vietnam'),
    ('Yemen', 'Yemen'),
    ('Zambia', 'Zambia'),
    ('Zimbabwe', 'Zimbabwe'),
]

# States/Provinces by country (major countries)
STATES_BY_COUNTRY = {
    'United States': [
        'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 
        'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 
        'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 
        'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 
        'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 
        'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 
        'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 
        'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 
        'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 
        'West Virginia', 'Wisconsin', 'Wyoming'
    ],
    'India': [
        'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
        'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
        'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
        'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
        'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
        'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli',
        'Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh', 'Lakshadweep',
        'Puducherry'
    ],
    'Canada': [
        'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick',
        'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia',
        'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan',
        'Yukon'
    ],
    'Australia': [
        'Australian Capital Territory', 'New South Wales', 'Northern Territory',
        'Queensland', 'South Australia', 'Tasmania', 'Victoria', 'Western Australia'
    ],
    'United Kingdom': [
        'England', 'Scotland', 'Wales', 'Northern Ireland'
    ],
    'Germany': [
        'Baden-Württemberg', 'Bavaria', 'Berlin', 'Brandenburg', 'Bremen',
        'Hamburg', 'Hesse', 'Lower Saxony', 'Mecklenburg-Vorpommern',
        'North Rhine-Westphalia', 'Rhineland-Palatinate', 'Saarland',
        'Saxony', 'Saxony-Anhalt', 'Schleswig-Holstein', 'Thuringia'
    ],
    'China': [
        'Anhui', 'Beijing', 'Chongqing', 'Fujian', 'Gansu', 'Guangdong',
        'Guangxi', 'Guizhou', 'Hainan', 'Hebei', 'Heilongjiang', 'Henan',
        'Hubei', 'Hunan', 'Inner Mongolia', 'Jiangsu', 'Jiangxi', 'Jilin',
        'Liaoning', 'Ningxia', 'Qinghai', 'Shaanxi', 'Shandong', 'Shanghai',
        'Shanxi', 'Sichuan', 'Tianjin', 'Tibet', 'Xinjiang', 'Yunnan', 'Zhejiang'
    ],
    'Brazil': [
        'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará',
        'Distrito Federal', 'Espírito Santo', 'Goiás', 'Maranhão',
        'Mato Grosso', 'Mato Grosso do Sul', 'Minas Gerais', 'Pará',
        'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio de Janeiro',
        'Rio Grande do Norte', 'Rio Grande do Sul', 'Rondônia', 'Roraima',
        'Santa Catarina', 'São Paulo', 'Sergipe', 'Tocantins'
    ],
    'Mexico': [
        'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche',
        'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'Durango', 'Guanajuato',
        'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico City', 'México', 'Michoacán',
        'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro',
        'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco',
        'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas'
    ],
    'Japan': [
        'Aichi', 'Akita', 'Aomori', 'Chiba', 'Ehime', 'Fukui', 'Fukuoka',
        'Fukushima', 'Gifu', 'Gunma', 'Hiroshima', 'Hokkaido', 'Hyogo',
        'Ibaraki', 'Ishikawa', 'Iwate', 'Kagawa', 'Kagoshima', 'Kanagawa',
        'Kochi', 'Kumamoto', 'Kyoto', 'Mie', 'Miyagi', 'Miyazaki', 'Nagano',
        'Nagasaki', 'Nara', 'Niigata', 'Oita', 'Okayama', 'Okinawa', 'Osaka',
        'Saga', 'Saitama', 'Shiga', 'Shimane', 'Shizuoka', 'Tochigi', 'Tokushima',
        'Tokyo', 'Tottori', 'Toyama', 'Wakayama', 'Yamagata', 'Yamaguchi', 'Yamanashi'
    ],
    'France': [
        'Auvergne-Rhône-Alpes', 'Bourgogne-Franche-Comté', 'Brittany', 'Centre-Val de Loire',
        'Corsica', 'Grand Est', 'Hauts-de-France', 'Île-de-France', 'Normandy',
        'Nouvelle-Aquitaine', 'Occitanie', 'Pays de la Loire', 'Provence-Alpes-Côte d\'Azur'
    ],
    'Italy': [
        'Abruzzo', 'Aosta Valley', 'Apulia', 'Basilicata', 'Calabria', 'Campania',
        'Emilia-Romagna', 'Friuli-Venezia Giulia', 'Lazio', 'Liguria', 'Lombardy',
        'Marche', 'Molise', 'Piedmont', 'Sardinia', 'Sicily', 'Tuscany',
        'Trentino-South Tyrol', 'Umbria', 'Veneto'
    ],
    'Spain': [
        'Andalusia', 'Aragon', 'Asturias', 'Balearic Islands', 'Basque Country',
        'Canary Islands', 'Cantabria', 'Castile and León', 'Castile-La Mancha',
        'Catalonia', 'Extremadura', 'Galicia', 'La Rioja', 'Madrid', 'Murcia',
        'Navarre', 'Valencia'
    ],
    'Argentina': [
        'Buenos Aires', 'Catamarca', 'Chaco', 'Chubut', 'Córdoba', 'Corrientes',
        'Entre Ríos', 'Formosa', 'Jujuy', 'La Pampa', 'La Rioja', 'Mendoza',
        'Misiones', 'Neuquén', 'Río Negro', 'Salta', 'San Juan', 'San Luis',
        'Santa Cruz', 'Santa Fe', 'Santiago del Estero', 'Tierra del Fuego',
        'Tucumán'
    ],
    'South Africa': [
        'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
        'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape'
    ],
    'Nigeria': [
        'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
        'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
        'Federal Capital Territory', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano',
        'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun',
        'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'
    ],
    'Pakistan': [
        'Azad Kashmir', 'Balochistan', 'Gilgit-Baltistan', 'Islamabad Capital Territory',
        'Khyber Pakhtunkhwa', 'Punjab', 'Sindh'
    ],
    'Indonesia': [
        'Aceh', 'Bali', 'Bangka Belitung Islands', 'Banten', 'Bengkulu', 'Central Java',
        'Central Kalimantan', 'Central Sulawesi', 'East Java', 'East Kalimantan',
        'East Nusa Tenggara', 'Gorontalo', 'Jakarta', 'Jambi', 'Lampung', 'Maluku',
        'North Kalimantan', 'North Maluku', 'North Sulawesi', 'North Sumatra', 'Papua',
        'Riau', 'Riau Islands', 'South Kalimantan', 'South Sulawesi', 'South Sumatra',
        'Southeast Sulawesi', 'West Java', 'West Kalimantan', 'West Nusa Tenggara',
        'West Papua', 'West Sulawesi', 'West Sumatra', 'Yogyakarta'
    ],
    'Malaysia': [
        'Johor', 'Kedah', 'Kelantan', 'Kuala Lumpur', 'Labuan', 'Malacca', 'Negeri Sembilan',
        'Pahang', 'Penang', 'Perak', 'Perlis', 'Putrajaya', 'Sabah', 'Sarawak', 'Selangor',
        'Terengganu'
    ],
    'Philippines': [
        'Abra', 'Agusan del Norte', 'Agusan del Sur', 'Aklan', 'Albay', 'Antique', 'Apayao',
        'Aurora', 'Basilan', 'Bataan', 'Batanes', 'Batangas', 'Benguet', 'Biliran', 'Bohol',
        'Bukidnon', 'Bulacan', 'Cagayan', 'Camarines Norte', 'Camarines Sur', 'Camiguin',
        'Capiz', 'Catanduanes', 'Cavite', 'Cebu', 'Cotabato', 'Davao de Oro', 'Davao del Norte',
        'Davao del Sur', 'Davao Occidental', 'Davao Oriental', 'Dinagat Islands', 'Eastern Samar',
        'Guimaras', 'Ifugao', 'Ilocos Norte', 'Ilocos Sur', 'Iloilo', 'Isabela', 'Kalinga',
        'La Union', 'Laguna', 'Lanao del Norte', 'Lanao del Sur', 'Leyte', 'Maguindanao',
        'Manila', 'Marinduque', 'Masbate', 'Metro Manila', 'Misamis Occidental', 'Misamis Oriental',
        'Mountain Province', 'Negros Occidental', 'Negros Oriental', 'Northern Samar', 'Nueva Ecija',
        'Nueva Vizcaya', 'Occidental Mindoro', 'Oriental Mindoro', 'Palawan', 'Pampanga', 'Pangasinan',
        'Quezon', 'Quirino', 'Rizal', 'Romblon', 'Samar', 'Sarangani', 'Siquijor', 'Sorsogon',
        'South Cotabato', 'Southern Leyte', 'Sultan Kudarat', 'Sulu', 'Surigao del Norte',
        'Surigao del Sur', 'Tarlac', 'Tawi-Tawi', 'Zambales', 'Zamboanga del Norte',
        'Zamboanga del Sur', 'Zamboanga Sibugay'
    ],
    'Thailand': [
        'Amnat Charoen', 'Ang Thong', 'Bangkok', 'Bueng Kan', 'Buri Ram', 'Chachoengsao',
        'Chai Nat', 'Chaiyaphum', 'Chanthaburi', 'Chiang Mai', 'Chiang Rai', 'Chon Buri',
        'Chumphon', 'Kalasin', 'Kamphaeng Phet', 'Kanchanaburi', 'Khon Kaen', 'Krabi',
        'Lampang', 'Lamphun', 'Loei', 'Lop Buri', 'Mae Hong Son', 'Maha Sarakham',
        'Mukdahan', 'Nakhon Nayok', 'Nakhon Pathom', 'Nakhon Phanom', 'Nakhon Ratchasima',
        'Nakhon Sawan', 'Nakhon Si Thammarat', 'Nan', 'Narathiwat', 'Nong Bua Lam Phu',
        'Nong Khai', 'Nonthaburi', 'Pathum Thani', 'Pattani', 'Phang Nga', 'Phatthalung',
        'Phayao', 'Phetchabun', 'Phetchaburi', 'Phichit', 'Phitsanulok', 'Phra Nakhon Si Ayutthaya',
        'Phrae', 'Phuket', 'Prachin Buri', 'Prachuap Khiri Khan', 'Ranong', 'Ratchaburi',
        'Rayong', 'Roi Et', 'Sa Kaeo', 'Sakon Nakhon', 'Samut Prakan', 'Samut Sakhon',
        'Samut Songkhram', 'Saraburi', 'Satun', 'Sing Buri', 'Si Sa Ket', 'Songkhla',
        'Sukhothai', 'Suphan Buri', 'Surat Thani', 'Surin', 'Tak', 'Trang', 'Trat',
        'Ubon Ratchathani', 'Udon Thani', 'Uthai Thani', 'Uttaradit', 'Yala', 'Yasothon'
    ],
    'Poland': [
        'Greater Poland', 'Kuyavian-Pomeranian', 'Lesser Poland', 'Lodz', 'Lower Silesian',
        'Lublin', 'Lubusz', 'Masovian', 'Opole', 'Podkarpackie', 'Podlaskie', 'Pomeranian',
        'Silesian', 'Swietokrzyskie', 'Warmian-Masurian', 'West Pomeranian'
    ],
    'Netherlands': [
        'Drenthe', 'Flevoland', 'Friesland', 'Gelderland', 'Groningen', 'Limburg',
        'North Brabant', 'North Holland', 'Overijssel', 'South Holland', 'Utrecht', 'Zeeland'
    ],
    'Belgium': [
        'Antwerp', 'Brussels-Capital', 'East Flanders', 'Flemish Brabant', 'Hainaut',
        'Liège', 'Limburg', 'Luxembourg', 'Namur', 'Walloon Brabant', 'West Flanders'
    ],
    'Switzerland': [
        'Aargau', 'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'Basel-Landschaft',
        'Basel-Stadt', 'Bern', 'Fribourg', 'Geneva', 'Glarus', 'Graubünden', 'Jura',
        'Lucerne', 'Neuchâtel', 'Nidwalden', 'Obwalden', 'Schaffhausen', 'Schwyz',
        'Solothurn', 'St. Gallen', 'Thurgau', 'Ticino', 'Uri', 'Valais', 'Vaud', 'Zug', 'Zurich'
    ],
    'Austria': [
        'Burgenland', 'Carinthia', 'Lower Austria', 'Salzburg', 'Styria', 'Tyrol',
        'Upper Austria', 'Vienna', 'Vorarlberg'
    ],
    'Turkey': [
        'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray', 'Amasya', 'Ankara',
        'Antalya', 'Ardahan', 'Artvin', 'Aydın', 'Balıkesir', 'Bartın', 'Batman', 'Bayburt',
        'Bilecik', 'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale', 'Çankırı',
        'Çorum', 'Denizli', 'Diyarbakır', 'Düzce', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum',
        'Eskişehir', 'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkâri', 'Hatay', 'Iğdır', 'Isparta',
        'Istanbul', 'İzmir', 'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars', 'Kastamonu', 'Kayseri',
        'Kırıkkale', 'Kırklareli', 'Kırşehir', 'Kilis', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya',
        'Manisa', 'Mardin', 'Mersin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye',
        'Rize', 'Sakarya', 'Samsun', 'Şanlıurfa', 'Siirt', 'Sinop', 'Şırnak', 'Sivas', 'Tekirdağ',
        'Tokat', 'Trabzon', 'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat', 'Zonguldak'
    ],
    'Egypt': [
        'Alexandria', 'Aswan', 'Asyut', 'Beheira', 'Beni Suef', 'Cairo', 'Dakahlia',
        'Damietta', 'Faiyum', 'Gharbia', 'Giza', 'Ismailia', 'Kafr El Sheikh', 'Luxor',
        'Matruh', 'Minya', 'Monufia', 'New Valley', 'North Sinai', 'Port Said', 'Qalyubia',
        'Qena', 'Red Sea', 'Sharqia', 'Sohag', 'South Sinai', 'Suez'
    ],
    'Kenya': [
        'Baringo', 'Bomet', 'Bungoma', 'Busia', 'Elgeyo-Marakwet', 'Embu', 'Garissa',
        'Homa Bay', 'Isiolo', 'Kajiado', 'Kakamega', 'Kericho', 'Kiambu', 'Kilifi',
        'Kirinyaga', 'Kisii', 'Kisumu', 'Kitui', 'Kwale', 'Laikipia', 'Lamu', 'Machakos',
        'Makueni', 'Mandera', 'Marsabit', 'Meru', 'Migori', 'Mombasa', 'Muranga', 'Nairobi',
        'Nakuru', 'Nandi', 'Narok', 'Nyamira', 'Nyandarua', 'Nyeri', 'Samburu', 'Siaya',
        'Taita-Taveta', 'Tana River', 'Tharaka-Nithi', 'Trans Nzoia', 'Turkana', 'Uasin Gishu',
        'Vihiga', 'Wajir', 'West Pokot'
    ],
    'Russia': [
        'Altai Krai', 'Altai Republic', 'Amur Oblast', 'Arkhangelsk Oblast', 'Astrakhan Oblast',
        'Bashkortostan', 'Belgorod Oblast', 'Bryansk Oblast', 'Buryatia', 'Chechen Republic',
        'Chelyabinsk Oblast', 'Chukotka', 'Chuvashia', 'Dagestan', 'Ingushetia', 'Irkutsk Oblast',
        'Ivanovo Oblast', 'Jewish Autonomous Oblast', 'Kabardino-Balkaria', 'Kaliningrad Oblast',
        'Kalmykia', 'Kaluga Oblast', 'Kamchatka Krai', 'Karachay-Cherkessia', 'Karelia',
        'Kemerovo Oblast', 'Khabarovsk Krai', 'Khakassia', 'Khanty-Mansi', 'Kirov Oblast',
        'Komi Republic', 'Kostroma Oblast', 'Krasnodar Krai', 'Krasnoyarsk Krai', 'Kurgan Oblast',
        'Kursk Oblast', 'Leningrad Oblast', 'Lipetsk Oblast', 'Magadan Oblast', 'Mari El',
        'Mordovia', 'Moscow', 'Moscow Oblast', 'Murmansk Oblast', 'Nenets', 'Nizhny Novgorod Oblast',
        'North Ossetia-Alania', 'Novgorod Oblast', 'Novosibirsk Oblast', 'Omsk Oblast',
        'Orenburg Oblast', 'Oryol Oblast', 'Penza Oblast', 'Perm Krai', 'Primorsky Krai',
        'Pskov Oblast', 'Rostov Oblast', 'Ryazan Oblast', 'Saint Petersburg', 'Sakha Republic',
        'Sakhalin Oblast', 'Samara Oblast', 'Saratov Oblast', 'Smolensk Oblast', 'Stavropol Krai',
        'Sverdlovsk Oblast', 'Tambov Oblast', 'Tatarstan', 'Tomsk Oblast', 'Tula Oblast',
        'Tuva Republic', 'Tver Oblast', 'Tyumen Oblast', 'Udmurtia', 'Ulyanovsk Oblast',
        'Vladimir Oblast', 'Volgograd Oblast', 'Vologda Oblast', 'Voronezh Oblast',
        'Yamalo-Nenets', 'Yaroslavl Oblast', 'Zabaykalsky Krai'
    ],
}

# Phone country codes - comprehensive list
PHONE_CODES = [
    ('', 'Select Code'),
    ('+93', '🇦🇫 +93 (AF)'),
    ('+355', '🇦🇱 +355 (AL)'),
    ('+213', '🇩🇿 +213 (DZ)'),
    ('+376', '🇦🇩 +376 (AD)'),
    ('+244', '🇦🇴 +244 (AO)'),
    ('+54', '🇦🇷 +54 (AR)'),
    ('+374', '🇦🇲 +374 (AM)'),
    ('+61', '🇦🇺 +61 (AU)'),
    ('+43', '🇦🇹 +43 (AT)'),
    ('+994', '🇦🇿 +994 (AZ)'),
    ('+973', '🇧🇭 +973 (BH)'),
    ('+880', '🇧🇩 +880 (BD)'),
    ('+375', '🇧🇾 +375 (BY)'),
    ('+32', '🇧🇪 +32 (BE)'),
    ('+501', '🇧🇿 +501 (BZ)'),
    ('+229', '🇧🇯 +229 (BJ)'),
    ('+975', '🇧🇹 +975 (BT)'),
    ('+591', '🇧🇴 +591 (BO)'),
    ('+387', '🇧🇦 +387 (BA)'),
    ('+267', '🇧🇼 +267 (BW)'),
    ('+55', '🇧🇷 +55 (BR)'),
    ('+673', '🇧🇳 +673 (BN)'),
    ('+359', '🇧🇬 +359 (BG)'),
    ('+226', '🇧🇫 +226 (BF)'),
    ('+257', '🇧🇮 +257 (BI)'),
    ('+855', '🇰🇭 +855 (KH)'),
    ('+237', '🇨🇲 +237 (CM)'),
    ('+1', '🇨🇦🇺🇸 +1 (CA/US)'),
    ('+236', '🇨🇫 +236 (CF)'),
    ('+235', '🇹🇩 +235 (TD)'),
    ('+56', '🇨🇱 +56 (CL)'),
    ('+86', '🇨🇳 +86 (CN)'),
    ('+57', '🇨🇴 +57 (CO)'),
    ('+506', '🇨🇷 +506 (CR)'),
    ('+385', '🇭🇷 +385 (HR)'),
    ('+53', '🇨🇺 +53 (CU)'),
    ('+357', '🇨🇾 +357 (CY)'),
    ('+420', '🇨🇿 +420 (CZ)'),
    ('+45', '🇩🇰 +45 (DK)'),
    ('+253', '🇩🇯 +253 (DJ)'),
    ('+593', '🇪🇨 +593 (EC)'),
    ('+20', '🇪🇬 +20 (EG)'),
    ('+503', '🇸🇻 +503 (SV)'),
    ('+240', '🇬🇶 +240 (GQ)'),
    ('+291', '🇪🇷 +291 (ER)'),
    ('+372', '🇪🇪 +372 (EE)'),
    ('+251', '🇪🇹 +251 (ET)'),
    ('+679', '🇫🇯 +679 (FJ)'),
    ('+358', '🇫🇮 +358 (FI)'),
    ('+33', '🇫🇷 +33 (FR)'),
    ('+241', '🇬🇦 +241 (GA)'),
    ('+995', '🇬🇪 +995 (GE)'),
    ('+49', '🇩🇪 +49 (DE)'),
    ('+233', '🇬🇭 +233 (GH)'),
    ('+30', '🇬🇷 +30 (GR)'),
    ('+502', '🇬🇹 +502 (GT)'),
    ('+224', '🇬🇳 +224 (GN)'),
    ('+245', '🇬🇼 +245 (GW)'),
    ('+592', '🇬🇾 +592 (GY)'),
    ('+509', '🇭🇹 +509 (HT)'),
    ('+504', '🇭🇳 +504 (HN)'),
    ('+36', '🇭🇺 +36 (HU)'),
    ('+354', '🇮🇸 +354 (IS)'),
    ('+91', '🇮🇳 +91 (IN)'),
    ('+62', '🇮🇩 +62 (ID)'),
    ('+98', '🇮🇷 +98 (IR)'),
    ('+964', '🇮🇶 +964 (IQ)'),
    ('+353', '🇮🇪 +353 (IE)'),
    ('+972', '🇮🇱 +972 (IL)'),
    ('+39', '🇮🇹 +39 (IT)'),
    ('+81', '🇯🇵 +81 (JP)'),
    ('+962', '🇯🇴 +962 (JO)'),
    ('+7', '🇰🇿🇷🇺 +7 (KZ/RU)'),
    ('+254', '🇰🇪 +254 (KE)'),
    ('+965', '🇰🇼 +965 (KW)'),
    ('+996', '🇰🇬 +996 (KG)'),
    ('+856', '🇱🇦 +856 (LA)'),
    ('+371', '🇱🇻 +371 (LV)'),
    ('+961', '🇱🇧 +961 (LB)'),
    ('+266', '🇱🇸 +266 (LS)'),
    ('+231', '🇱🇷 +231 (LR)'),
    ('+218', '🇱🇾 +218 (LY)'),
    ('+423', '🇱🇮 +423 (LI)'),
    ('+370', '🇱🇹 +370 (LT)'),
    ('+352', '🇱🇺 +352 (LU)'),
    ('+389', '🇲🇰 +389 (MK)'),
    ('+261', '🇲🇬 +261 (MG)'),
    ('+265', '🇲🇼 +265 (MW)'),
    ('+60', '🇲🇾 +60 (MY)'),
    ('+960', '🇲🇻 +960 (MV)'),
    ('+223', '🇲🇱 +223 (ML)'),
    ('+356', '🇲🇹 +356 (MT)'),
    ('+692', '🇲🇭 +692 (MH)'),
    ('+222', '🇲🇷 +222 (MR)'),
    ('+230', '🇲🇺 +230 (MU)'),
    ('+52', '🇲🇽 +52 (MX)'),
    ('+691', '🇫🇲 +691 (FM)'),
    ('+373', '🇲🇩 +373 (MD)'),
    ('+377', '🇲🇨 +377 (MC)'),
    ('+976', '🇲🇳 +976 (MN)'),
    ('+382', '🇲🇪 +382 (ME)'),
    ('+212', '🇲🇦 +212 (MA)'),
    ('+258', '🇲🇿 +258 (MZ)'),
    ('+95', '🇲🇲 +95 (MM)'),
    ('+264', '🇳🇦 +264 (NA)'),
    ('+674', '🇳🇷 +674 (NR)'),
    ('+977', '🇳🇵 +977 (NP)'),
    ('+31', '🇳🇱 +31 (NL)'),
    ('+64', '🇳🇿 +64 (NZ)'),
    ('+505', '🇳🇮 +505 (NI)'),
    ('+227', '🇳🇪 +227 (NE)'),
    ('+234', '🇳🇬 +234 (NG)'),
    ('+850', '🇰🇵 +850 (KP)'),
    ('+47', '🇳🇴 +47 (NO)'),
    ('+968', '🇴🇲 +968 (OM)'),
    ('+92', '🇵🇰 +92 (PK)'),
    ('+680', '🇵🇼 +680 (PW)'),
    ('+970', '🇵🇸 +970 (PS)'),
    ('+507', '+507 (PA)'),
    ('+675', '+675 (PG)'),
    ('+595', '+595 (PY)'),
    ('+51', '+51 (PE)'),
    ('+63', '+63 (PH)'),
    ('+48', '+48 (PL)'),
    ('+351', '+351 (PT)'),
    ('+974', '+974 (QA)'),
    ('+40', '+40 (RO)'),
    ('+250', '+250 (RW)'),
    ('+966', '+966 (SA)'),
    ('+221', '+221 (SN)'),
    ('+381', '+381 (RS)'),
    ('+248', '+248 (SC)'),
    ('+232', '+232 (SL)'),
    ('+65', '+65 (SG)'),
    ('+421', '+421 (SK)'),
    ('+386', '+386 (SI)'),
    ('+677', '+677 (SB)'),
    ('+252', '+252 (SO)'),
    ('+27', '+27 (ZA)'),
    ('+82', '+82 (KR)'),
    ('+211', '+211 (SS)'),
    ('+34', '+34 (ES)'),
    ('+94', '+94 (LK)'),
    ('+249', '+249 (SD)'),
    ('+597', '+597 (SR)'),
    ('+268', '+268 (SZ)'),
    ('+46', '+46 (SE)'),
    ('+41', '🇨🇭 +41 (CH)'),
    ('+963', '🇸🇾 +963 (SY)'),
    ('+886', '🇹🇼 +886 (TW)'),
    ('+992', '🇹🇯 +992 (TJ)'),
    ('+255', '🇹🇿 +255 (TZ)'),
    ('+66', '🇹🇭 +66 (TH)'),
    ('+670', '🇹🇱 +670 (TL)'),
    ('+228', '🇹🇬 +228 (TG)'),
    ('+676', '🇹🇴 +676 (TO)'),
    ('+216', '🇹🇳 +216 (TN)'),
    ('+90', '🇹🇷 +90 (TR)'),
    ('+993', '🇹🇲 +993 (TM)'),
    ('+688', '🇹🇻 +688 (TV)'),
    ('+256', '🇺🇬 +256 (UG)'),
    ('+380', '🇺🇦 +380 (UA)'),
    ('+971', '🇦🇪 +971 (AE)'),
    ('+44', '🇬🇧 +44 (GB)'),
    ('+598', '🇺🇾 +598 (UY)'),
    ('+998', '🇺🇿 +998 (UZ)'),
    ('+678', '🇻🇺 +678 (VU)'),
    ('+58', '🇻🇪 +58 (VE)'),
    ('+84', '🇻🇳 +84 (VN)'),
    ('+967', '🇾🇪 +967 (YE)'),
    ('+260', '🇿🇲 +260 (ZM)'),
    ('+263', '🇿🇼 +263 (ZW)'),
]
